### ISSUE TITLE
最新版本会出现error 500的错误

### ISSUE THREAD

**Issue by devsea** [jinzhe/gum#1]
尝试使用最新版本安装，首页会提示error 500，不会重定向到安装界面开启display_errors后会提示Parse error: syntax error, unexpected '?' in /var/dir/index.php on line 11

文件定位到这一行 $action = $uri[2] ?? "";

另外能否建议在安装界面下 某些基本信息不作判断~

**Comment by devsea** [comment]
好像是因为我的PHP版本为5.6的问题，这个不兼容PHP 7以下的环境了吗？

**Comment by jinzhe** [comment]
现在强制使用php7以上版本
