### ISSUE TITLE
全新安装新版本出现SQLSTATE[21S01]: Insert value list does not match column list

### ISSUE THREAD

**Issue by devsea** [jinzhe/gum#3]
Fatal error: Uncaught PDOException: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 3 in /var//htdocs/core/db.php:134 Stack trace: #0 /var/htdocs/core/db.php(134): PDO->exec('\nINSERT INTO `l...') #1 /var/htdocs/install/index.php(54): db->exec('\nINSERT INTO `l...') #2 {main} thrown in /var/htdocs/core/db.php on line 134

这个应该是创建数据库字段和列不一致吧

**Comment by jinzhe** [comment]
是的，上次手动改了写入link 表少了个字段值。
